commit fs at sheet
opencurve/curve-book pull request #34
Opened 2023-10-11 02:36 UTC by caoxianfei1

2023-10-11 03:43 UTC, aspirer requested changes
1. 补充客户端相关操作指导
2. 服务端操作的影响，尤其是metaserver的，需要特别注意，会影响io，风险要提示到位，尤其是各种隐藏风险（比如重启单个ms和全部ms影响肯定不一样的，升级ms的场景，会不会影响io也要确认）
3. 集群健康状态检查这个步骤有点问题，如果集群在操作的时候就是不健康的，你这个操作能不能做？如能做，那做完之后集群还是不健康的，不能通过OK来判断了；如果不能做，那要写清楚做这些操作的前置条件要求，比如集群状态必须是OK才能做这个操作。
4. 其他建议参考具体的review评论

2023-10-11 03:43 UTC, aspirer commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/01-curvefs-controlplan-start-mds.md
> +
- 时间: 无
- 业务方: 无
- 影响主题: 无
- 用户：无

这部分格式稍微改下吧，还有下面的11也类似，其他操作也都改下。

2023-10-11 03:43 UTC, aspirer commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/02-curvefs-controlplan-stop-mds.md
> +   结果输出有下面字样则集群健康：Cluster health is:  ok
停掉一个mds集群状态还能保持ok吗？这个确认下？

2023-10-11 03:43 UTC, aspirer commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/03-curvefs-controlplan-restart-mds.md
> +## Curve 重启mds
去掉一个#改成一级标题，否则文档网站上渲染会失败。

2023-10-11 03:43 UTC, aspirer commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/03-curvefs-controlplan-restart-mds.md
> +   $ curve fs status cluster
这里的输出和检查方法描述，跟上面几个不一样，保持一致吧

2023-10-11 03:43 UTC, aspirer commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/03-curvefs-controlplan-restart-mds.md
> +
重启全部mds也没有影响吗？

2023-10-11 03:43 UTC, aspirer commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/02-curvefs-controlplan-stop-mds.md
> +时间: 无
停止全部mds应该有影响吧？

2023-10-11 03:43 UTC, aspirer commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/02-curvefs-controlplan-stop-mds.md
> +数据面: IO可能有短暂时间抖动
停止全部mds和部分mds的影响应该不一样吧？
另外停止mds对io的影响是啥？为啥影响io？可以详细描述下。

2023-10-11 03:43 UTC, aspirer commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/03-curvefs-controlplan-restart-mds.md
> +数据面: IO可能有短暂时间抖动
同上

2023-10-11 03:43 UTC, aspirer commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/04-curvefs-controlplan-config-mds.md
> +
同上

2023-10-11 03:43 UTC, aspirer commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/04-curvefs-controlplan-config-mds.md
> +数据面: IO可能有短暂时间抖动
同上

2023-10-11 03:43 UTC, aspirer commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/05-curvefs-controlplan-upgrade-mds.md
> +4. 查看集群是否健康（Cluster health is:  ok）：
同上

2023-10-11 03:43 UTC, aspirer commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/05-curvefs-controlplan-upgrade-mds.md
> +
同上

2023-10-11 03:43 UTC, aspirer commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/05-curvefs-controlplan-upgrade-mds.md
> +数据面: IO可能有短暂时间抖动
同上

2023-10-11 03:43 UTC, aspirer commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/06-curvefs-controlplan-back-mds.md
> +管控面: 管理服务短暂不可用
同上

2023-10-11 03:43 UTC, aspirer commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/06-curvefs-controlplan-back-mds.md
> +时间: 无
同上

2023-10-11 03:43 UTC, aspirer commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/07-curvefs-dataplan-start-metaserver.md
> +数据面: IO可能有短暂时间抖动
具体影响的原因和范围，可以详细描述下

2023-10-11 03:43 UTC, aspirer commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/08-curvefs-dataplan-stop-metaserver.md
> +时间: 无
同上

2023-10-11 03:43 UTC, aspirer commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/08-curvefs-dataplan-stop-metaserver.md
> +数据面: IO可能有短暂时间抖动，或者集群不健康，导致客户端IO失败
同上

2023-10-11 03:43 UTC, aspirer commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/08-curvefs-dataplan-stop-metaserver.md
> +   $ curveadm stop --role metaserver
停止所有metaserver，影响太大了吧？这个不需要特别说明吗？而且下面的影响和风险也没写出来。

2023-10-11 03:43 UTC, aspirer commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/08-curvefs-dataplan-stop-metaserver.md
> +   结果输出有下面字样则集群健康：Cluster health is:  ok
这个检查结果明显应该是集群不健康吧？肯定不是OK才对

2023-10-11 03:45 UTC, aspirer commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/01-curvefs-controlplan-start-mds.md
> +
改成无序列表

2023-10-11 03:46 UTC, aspirer commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/03-curvefs-controlplan-restart-mds.md
> +## Curve 重启mds
其他md文档也一样改改

2023-10-30 03:17 UTC, wu-hanqing commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/05-curvefs-controlpanel-upgrade-mds.md
> +   $ curveadm upgrade --role mds
修改配置中的 `curveadm reload --role mds` 是滚动操作的吗？还是所有mds同时重启了？

2023-10-30 03:17 UTC, wu-hanqing commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/18-curvefs-client-umount.md
> +* 恢复能力: 无需恢复
卸载操作会预期导致文件系统不可用，需要业务方发起需求。

看下怎么备注一下比较合适。

2023-10-30 03:17 UTC, wu-hanqing commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/18-curvefs-client-umount.md
> +12. 参考回滚策略: 无
重新挂载？

2023-10-30 03:17 UTC, wu-hanqing commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/16-curvefs-datapanel-migrate.md
> +12. 参考回滚策略: 无
这个有可以参考的回滚操作吗？

2023-10-30 03:17 UTC, wu-hanqing commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/15-curvefs-datapanel-change-disk.md
> +             data_dir: /mnt/curvefs/data/${service_role} # 新盘路径
换盘之后，会导致目录发生变化吗？比如原来的data_dir是/data/metaserver2，坏盘更换之后，是什么？

2023-10-30 03:19 UTC, wu-hanqing commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/02-curvefs-controlpanel-stop-mds.md
> +   $ curveadm stop --host <hostip> --role mds
这里的 <hostip> 填 hosts.yaml 中的 host和hostname都可以吗？

2023-10-31 03:08 UTC, caoxianfei1 commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/05-curvefs-controlpanel-upgrade-mds.md
> +   $ curveadm upgrade --role mds
不是滚动的，是同时重启的。
在reload里面加了风险提示和影响。

2023-10-31 03:12 UTC, caoxianfei1 commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/18-curvefs-client-umount.md
> +12. 参考回滚策略: 无
fixed.

2023-10-31 03:16 UTC, caoxianfei1 commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/18-curvefs-client-umount.md
> +* 恢复能力: 无需恢复
fixed

2023-10-31 06:02 UTC, caoxianfei1 commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/02-curvefs-controlpanel-stop-mds.md
> +   $ curveadm stop --host <hostip> --role mds
要填hostname

2023-10-31 06:02 UTC, caoxianfei1 commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/02-curvefs-controlpanel-stop-mds.md
> +   $ curveadm stop --host <hostip> --role mds
fixed

2023-10-31 06:19 UTC, caoxianfei1 commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/15-curvefs-datapanel-change-disk.md
> +             data_dir: /mnt/curvefs/data/${service_role} # 新盘路径
不会发生变化，这里不用添加，已修改。

2023-11-02 08:42 UTC, aspirer commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/08-curvebs-datapanel-stop-chunkserver.md
> +* 情况2：同时停掉所有的mds服务（一般不会做此操作）
chunkserver

2023-11-02 08:42 UTC, aspirer commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/09-curvebs-datapanel-restart-chunkserver.md
> +      2 .如果当前集群处于warn状态，则需要使用工具（如下命令）判断是否因为当前mds服务异常导致，如果是chunkserver问题，则不要执行后续步骤。
1）2 . --> 2.
2）当前mds --> 当前chunkserver
3）也有可能是因为这个chunkserver有问题才尝试重启的。

2023-11-02 08:42 UTC, aspirer commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/09-curvebs-datapanel-restart-chunkserver.md
> +   结果输出有下面字样则集群健康：Cluster health is:  ok
可能就是因为某个chunkserver有异常才需要重启的

2023-11-02 08:42 UTC, aspirer commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/09-curvebs-datapanel-restart-chunkserver.md
> +   结果输出有下面字样则集群健康：Cluster health is:  ok
分正常重启和异常重启两种情况吧

2023-11-02 08:42 UTC, aspirer commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/09-curvebs-datapanel-restart-chunkserver.md
> +      3. 如果集群处于error状态，则重启chunkserver可能是无意义操作，所以不要执行后续步骤。
也有可能重启chunkserver就是为了解决error问题？

2023-11-02 08:42 UTC, aspirer commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/09-curvebs-datapanel-restart-chunkserver.md
> +* 情况1：重启部分chunkserver服务
还需要考虑故障域问题，如果重启的是3副本域的3个chunkserver，那还是会影响io的（会io hang）。
另外重启一个chunkserver或者一个副本域的chunkserver也会造成短暂的io抖动。

2023-11-02 08:42 UTC, aspirer commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/09-curvebs-datapanel-restart-chunkserver.md
> +* 情况2：同时重启所有的chunkserver服务
这个一般不建议这么操作，会导致io hang

2023-11-02 08:42 UTC, aspirer commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/09-curvebs-datapanel-restart-chunkserver.md
> +* 情况1：重启部分chunkserver服务
同上

2023-11-02 08:42 UTC, aspirer commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/09-curvebs-datapanel-restart-chunkserver.md
> +
应该是io hang而不是io 错误。

2023-11-02 08:42 UTC, aspirer commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/10-curvebs-datapanel-config-chunkserver.md
> +      2 .如果当前集群处于warn状态，则需要使用工具（如下命令）判断是否是因为当前chunkserver服务异常导致，如果是chunkserver问题，则不要进行下面操作。
2 . --> 2.

上面几个地方复制的也有这个问题，一起改掉吧

2023-11-02 08:42 UTC, aspirer commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/10-curvebs-datapanel-config-chunkserver.md
> +   结果输出有下面字样则集群健康：Cluster health is:  ok
同上，也有可能是有异常才修改配置。

2023-11-02 08:42 UTC, aspirer commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/10-curvebs-datapanel-config-chunkserver.md
> +   结果输出有下面字样则集群健康：Cluster health is:  ok
总之如果不是ok状态，就要确认是否符合预期前提条件（就是为了解决异常才做的操作，或者集群当前状态和本次操作不冲突或者互不相干，比如集群因为某个物理池有坏盘warn了，但本次重启的是另外一个物理池的chunkserver，这就是互不相干的，或者mds挂了一个也是互不相干。）。

2023-11-02 08:42 UTC, aspirer commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/10-curvebs-datapanel-config-chunkserver.md
> +    提醒：该操作会重启机器中的所有mds服务，所以在执行下列操作时，可能会导致IO短暂时间的不可用。
mds --> chunkserver

2023-11-02 08:42 UTC, aspirer commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/10-curvebs-datapanel-config-chunkserver.md
> +    提醒：该操作会重启机器中的所有mds服务，所以在执行下列操作时，可能会导致IO短暂时间的不可用。
最好讲一下reload操作的具体执行过程，比如会重启docker？
另外批量reload，是滚动发布吗？还是并行的？
如果是滚动的话会等待前面一个chunkserver变成正常状态再reload下一个吗？这与该操作的影响和风险有关系。

2023-11-02 08:42 UTC, aspirer commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/10-curvebs-datapanel-config-chunkserver.md
> +
这要看reload、restart的具体操作流程吧？如果是等待前面一个变成正常了再滚动下个，好像跟reload、restart单个类似？
批量重启操作也类似，确认下看要不要修改描述。

2023-11-02 08:42 UTC, aspirer commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/11-curvebs-datapanel-upgrade-chunkserver.md
> +   结果输出有下面字样则集群健康：Cluster health is:  ok
升级操作是要首先保证集群处于ok状态的，如果不ok，不建议升级。

2023-11-02 08:42 UTC, aspirer commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/11-curvebs-datapanel-upgrade-chunkserver.md
> +   结果输出有下面字样则集群健康：Cluster health is:  ok
另外升级前最好确认下版本的兼容性，有些版本可能不能升级到某些高级版本。比如curvebs 1.0 到 1.2 就不兼容，需要做额外的准备操作。这方面加一个提示就行。

2023-11-02 08:42 UTC, aspirer commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/11-curvebs-datapanel-upgrade-chunkserver.md
> +   提示：`curveadm upgrade --role chunkserver` 默认是滚动升级集群每一个chunkserver服务，用户在升级完一个chunkserver服务后 需要进入容器内确定集群是否健康。如果集群是健康的话，再输入yes开始升级下一个服务。
看起来这个滚动操作有个确认过程，批量reload或者restart有吗？最好也有吧。

确认集群是否健康不一定要进容器内吧？curve命令行可以外面操作？

2023-11-02 08:42 UTC, aspirer commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/11-curvebs-datapanel-upgrade-chunkserver.md
> +
升级操作的影响和风险更大吧？这方面至少得参考restart操作吧？io 抖动是肯定的。

2023-11-02 08:42 UTC, aspirer commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/12-curvebs-datapanel-back-chunkserver.md
> +10. 参考影响:
同上

2023-11-02 08:42 UTC, aspirer commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/13-curvebs-datapanel-upgrade.md
> +# Curve 升级服务端
这里的服务端是指具体哪个服务？mds？写清楚具体哪个或者哪几个服务吧

2023-11-02 08:42 UTC, aspirer commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/12-curvebs-datapanel-back-chunkserver.md
> +# Curve 回退chunkserver
文件名叫xxx-downgrade-chunkserver.md更合适？

2023-11-02 08:42 UTC, aspirer commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/13-curvebs-datapanel-upgrade.md
> +	 --id: 升级指定 id 的服务
这里的缩进跟下面两行不一致，其他文件也有几个地方有类似问题，一起看下

2023-11-02 08:42 UTC, aspirer commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/13-curvebs-datapanel-upgrade.md
> +# Curve 升级服务端
看起来是打算所有有服务端一起升级，按role指定升级吧。
如果是这样，这个文档和单独升级chunkserver的是否重复了？要不要合并或者拆开成一个role一个文档？

2023-11-02 08:42 UTC, aspirer commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/13-curvebs-datapanel-upgrade.md
> +
升级服务端的影响和风险肯定是有的，至少跟重启类似，甚至还要大。参考下之前at工单模板里面的升级服务端的影响吧。

2023-11-02 08:42 UTC, aspirer commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/14-curvebs-datapanel-scaleout.md
> +* 数据面: IO可能有短暂抖动
扩容应该不会造成io抖动吧？具体问下汉卿

2023-11-02 08:42 UTC, aspirer commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/14-curvebs-datapanel-scaleout.md
> +           replicas: 3
replicas是否已经改成了更合适的instances了？我记得开发者活动里有这个题目？如果能用instances最好不要用replicas，容易跟副本数量搞混。

2023-11-02 08:42 UTC, aspirer commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/14-curvebs-datapanel-scaleout.md
> +2. 版本号: v1.2.6/v1.2.7
突然想起来，这个版本是curve版本，是不是还要加上curveadm版本？比如xx版本或以上？不能每次发布新版本都修改这里的版本号吧？

2023-11-02 08:42 UTC, aspirer commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/15-curvebs-datapanel-change-disk.md
> +   结果输出有下面字样则集群健康：Cluster health is:  ok
集群变成ok状态是否需要等数据恢复完毕？如果是，可能会需要一段时间，具体问下汉卿他们吧。

2023-11-02 08:42 UTC, aspirer commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/15-curvebs-datapanel-change-disk.md
> +* 数据面: IO可能有短暂时间抖动
恢复期间应该io都会有一定的影响？可能不是短暂的吧？只是影响不会造成io hang，而是轻微抖动，具体问下汉卿

2023-11-02 08:42 UTC, aspirer commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/16-curvebs-datapanel-migrate.md
> +		 kind: curvebs
这段缩进跟下面的错开了，改下

2023-11-02 08:42 UTC, aspirer commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/16-curvebs-datapanel-migrate.md
> +	 * 每一次只能迁移同一种角色的其中一个服务
缩进

2023-11-02 08:42 UTC, aspirer commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/16-curvebs-datapanel-migrate.md
> +* 数据面: IO可能有短暂时间抖动
可能不是短暂抖动吧。

这个操作的具体执行原理是先把某个chunkserver下线踢盘，再在另外一个节点上加盘恢复数据？原理可以在参考影响里描述下。其他有类似io抖动风险的操作，都可以简单描述下操作原理。

2023-11-02 08:42 UTC, aspirer commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/17-curvebs-client-map.md
> +# Curve map卷
应该是挂载nbd盘到物理机吧？map卷不符合通常叫法。

2023-11-02 08:42 UTC, aspirer commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/18-curvebs-client-unmap.md
> +# Curve unmap卷
从物理机卸载nbd盘

2023-11-02 08:42 UTC, aspirer commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/19-curvebs-controlpanel-start-snapshot.md
> +# Curve 启动snapshotclone
参考启动mds的修改意见

2023-11-02 08:42 UTC, aspirer commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/20-curvebs-controlpanel-stop-snapshot.md
> +# Curve 停止snapshotclone
参考停止mds的意见，不过影响跟停止mds有区别，那个可能停止全部mds会影响io，这个不会，但会影响打快照或者从快照clone卷。

2023-11-02 08:42 UTC, aspirer commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/01-curvefs-controlpanel-start-mds.md
> +# Curve 启动mds
参考bs的启动mds修改建议，下面的停止、升级、修改配置，也是类似的参考下bs的。

2023-11-02 08:42 UTC, aspirer commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/11-curvefs-datapanel-upgrade-metaserver.md
> +
影响要更详细，停止、重启、升级ms 不会没有影响的，元数据操作肯定有影响。跟chunkserver类似，参考下。

2023-11-02 08:42 UTC, aspirer commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/15-curvefs-datapanel-change-disk.md
> +* 数据面: IO可能有短暂时间抖动
写清楚是元数据io？

2023-11-02 08:42 UTC, aspirer commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/16-curvefs-datapanel-migrate.md
> +
参考下bs的建议

2023-11-02 08:42 UTC, aspirer commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/17-curvefs-client-mount.md
> +
改为挂载文件系统？

2023-11-06 03:24 UTC, caoxianfei1 commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/12-curvebs-datapanel-back-chunkserver.md
> +# Curve 回退chunkserver
fixed.

2023-11-06 03:24 UTC, caoxianfei1 commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/13-curvebs-datapanel-upgrade.md
> +# Curve 升级服务端
fixed. 
已经把这个去掉了，按照role进行升级。

2023-11-06 03:25 UTC, caoxianfei1 commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/11-curvebs-datapanel-upgrade-chunkserver.md
> +   提示：`curveadm upgrade --role chunkserver` 默认是滚动升级集群每一个chunkserver服务，用户在升级完一个chunkserver服务后 需要进入容器内确定集群是否健康。如果集群是健康的话，再输入yes开始升级下一个服务。
目前curveadm 是upgrade操作是滚动，reload和restart都是同时加载和重启的。

2023-11-06 03:25 UTC, caoxianfei1 commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/11-curvebs-datapanel-upgrade-chunkserver.md
> +   结果输出有下面字样则集群健康：Cluster health is:  ok
fixed.

2023-11-06 03:27 UTC, caoxianfei1 commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/10-curvebs-datapanel-config-chunkserver.md
> +
curveadm的reload如果指定role的话是全部同时批量加载配置然后重启重启、所以这里分成了两个情况。
1. reload某个/某几个chunkserver
2.按照--role chunkserver指定的话，则是同时会重启

2023-11-06 03:28 UTC, caoxianfei1 commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/10-curvebs-datapanel-config-chunkserver.md
> +    提醒：该操作会重启机器中的所有mds服务，所以在执行下列操作时，可能会导致IO短暂时间的不可用。
fixed.
reload是同时进行的，所以下面的影响和风险分成了两种情况。

2023-11-06 03:30 UTC, caoxianfei1 commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/10-curvebs-datapanel-config-chunkserver.md
> +   结果输出有下面字样则集群健康：Cluster health is:  ok
Agree!
It has been fixed and update all related descriptions in other documents.

2023-11-06 03:30 UTC, caoxianfei1 commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/10-curvebs-datapanel-config-chunkserver.md
> +      2 .如果当前集群处于warn状态，则需要使用工具（如下命令）判断是否是因为当前chunkserver服务异常导致，如果是chunkserver问题，则不要进行下面操作。
fixed.

2023-11-06 03:30 UTC, caoxianfei1 commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/09-curvebs-datapanel-restart-chunkserver.md
> +
fixed.

2023-11-06 03:31 UTC, caoxianfei1 commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/09-curvebs-datapanel-restart-chunkserver.md
> +* 情况2：同时重启所有的chunkserver服务
fixed.
已经加上风险提示和影响。

2023-11-06 03:32 UTC, caoxianfei1 commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/09-curvebs-datapanel-restart-chunkserver.md
> +      3. 如果集群处于error状态，则重启chunkserver可能是无意义操作，所以不要执行后续步骤。
fixed.
其他相似的描述也已修改。

2023-11-06 03:32 UTC, caoxianfei1 commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/09-curvebs-datapanel-restart-chunkserver.md
> +   结果输出有下面字样则集群健康：Cluster health is:  ok
fixed.

2023-11-06 03:32 UTC, caoxianfei1 commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/09-curvebs-datapanel-restart-chunkserver.md
> +      2 .如果当前集群处于warn状态，则需要使用工具（如下命令）判断是否因为当前mds服务异常导致，如果是chunkserver问题，则不要执行后续步骤。
all fixed.

2023-11-06 03:32 UTC, caoxianfei1 commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/08-curvebs-datapanel-stop-chunkserver.md
> +* 情况2：同时停掉所有的mds服务（一般不会做此操作）
fixed.

2023-11-06 03:35 UTC, caoxianfei1 commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/13-curvebs-datapanel-upgrade.md
> +	 --id: 升级指定 id 的服务
fixed.

2023-11-06 03:36 UTC, caoxianfei1 commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/14-curvebs-datapanel-scaleout.md
> +2. 版本号: v1.2.6/v1.2.7
curveadm版本号已加。
curve版本号写作 `v1.2.6+`

2023-11-06 03:36 UTC, caoxianfei1 commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/15-curvebs-datapanel-change-disk.md
> +   结果输出有下面字样则集群健康：Cluster health is:  ok
已确认。
老的at工单没有这一步检查操作，而是判断chunkserver服务起来即可。

2023-11-06 03:37 UTC, caoxianfei1 commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/16-curvebs-datapanel-migrate.md
> +		 kind: curvebs
fixed.

2023-11-06 03:37 UTC, caoxianfei1 commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/16-curvebs-datapanel-migrate.md
> +	 * 每一次只能迁移同一种角色的其中一个服务
fixed.

2023-11-06 03:37 UTC, caoxianfei1 commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/17-curvebs-client-map.md
> +# Curve map卷
已修正。

2023-11-06 03:37 UTC, caoxianfei1 commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/18-curvebs-client-unmap.md
> +# Curve unmap卷
fixed.

2023-11-06 03:37 UTC, caoxianfei1 commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/19-curvebs-controlpanel-start-snapshot.md
> +# Curve 启动snapshotclone
fixed.

2023-11-06 03:37 UTC, caoxianfei1 commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/20-curvebs-controlpanel-stop-snapshot.md
> +# Curve 停止snapshotclone
fixed.

2023-11-06 03:38 UTC, caoxianfei1 commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/01-curvefs-controlpanel-start-mds.md
> +# Curve 启动mds
fixed.
已经对照修改。

2023-11-06 03:38 UTC, caoxianfei1 commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/16-curvefs-datapanel-migrate.md
> +
fixed.

2023-11-06 03:38 UTC, caoxianfei1 commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/17-curvefs-client-mount.md
> +
fixed.

2023-11-06 03:42 UTC, caoxianfei1 commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/14-curvebs-datapanel-scaleout.md
> +           replicas: 3
是的，但是还没有合到v0.2.1和v0.3.0的release版本中，所以这里还是保留了原来的字段。

2023-11-06 07:57 UTC, caoxianfei1 commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/09-curvebs-datapanel-restart-chunkserver.md
> +* 情况1：重启部分chunkserver服务
fixed.

2023-11-06 07:57 UTC, caoxianfei1 commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/09-curvebs-datapanel-restart-chunkserver.md
> +* 情况1：重启部分chunkserver服务
fixed.

2023-11-06 08:12 UTC, caoxianfei1 commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/11-curvebs-datapanel-upgrade-chunkserver.md
> +
fixed.

2023-11-06 08:12 UTC, caoxianfei1 commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/12-curvebs-datapanel-back-chunkserver.md
> +10. 参考影响:
fixed.

2023-11-06 08:14 UTC, caoxianfei1 commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/13-curvebs-datapanel-upgrade.md
> +
fixed.

2023-11-06 09:02 UTC, caoxianfei1 commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/16-curvebs-datapanel-migrate.md
> +* 数据面: IO可能有短暂时间抖动
// 这个操作的具体执行原理是先把某个chunkserver下线踢盘，再在另外一个节点上加盘恢复数据？
是的，就是换节点的操作。

加了原理描述。

2023-11-14 09:31 UTC, SeanHai commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/01-curvebs-controlpanel-start-mds.md
> +1. 查看集群状态和指定节点的mds状态：
`集群状态` -> `集群服务状态`

2023-11-14 09:31 UTC, SeanHai commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/01-curvebs-controlpanel-start-mds.md
> +3. 再次查看集群状态，查看指定mds服务是否启动成功（Status为Up状态）：
Ditto and check all, Distinguish between `集群状态` and `集群服务状态`

2023-11-14 09:31 UTC, SeanHai commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/02-curvebs-controlpanel-stop-mds.md
> +  * 恢复能力: 无需回复
`需要拉起mds` ?

2023-11-14 09:31 UTC, SeanHai commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/04-curvebs-controlpanel-config-mds.md
> +    提醒：该操作会重启机器中的所有mds服务，所以在执行下列操作时，可能会导致IO短暂时间的抖动。
确认结果是？reload是同时全部实例一起吧？

2023-11-14 09:31 UTC, SeanHai commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/05-curvebs-controlpanel-upgrade-mds.md
> +   $ cp topology.yaml topology.yaml.bak
建议备份后的名称一致，上面叫topology-old.yaml

2023-11-14 09:31 UTC, SeanHai commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/09-curvebs-datapanel-restart-chunkserver.md
> +* 情况2：重启某个副本域的所有chunkserver
情况2就是情况1后面的第二种情况，不会有影响。这里可以补充，重启涉及多个副本域的chunkserver

2023-11-14 09:31 UTC, SeanHai commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/09-curvebs-datapanel-restart-chunkserver.md
> +* 情况2：重启某个副本域的所有chunkserver
Ditto

2023-11-14 09:31 UTC, SeanHai commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/12-curvebs-datapanel-downgrade-chunkserver.md
> +* 情况2：回退某个副本域的所有chunkserver
涉及多个副本域的chunkserver

2023-11-14 09:31 UTC, SeanHai commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/12-curvebs-datapanel-downgrade-chunkserver.md
> +* 情况2：回退某个副本域的所有chunkserver
Ditto

2023-11-14 09:31 UTC, SeanHai commented
miss the file 13-*** under BS and FS

2023-11-14 09:39 UTC, SeanHai commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/08-curvefs-datapanel-stop-metaserver.md
> +* 情况1：停止部分metaserver服务
不能夸副本域，同一个副本域中的部分是ok的，如果跨域可能造成io卡住

2023-11-14 09:39 UTC, SeanHai commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/08-curvefs-datapanel-stop-metaserver.md
> +* 情况1：停止部分metaserver服务
Ditto

2023-11-14 09:39 UTC, SeanHai commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/09-curvefs-datapanel-restart-metaserver.md
> +* 情况2：重启某个副本域的所有metaserver
Ditto

2023-11-14 09:39 UTC, SeanHai commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/09-curvefs-datapanel-restart-metaserver.md
> +* 情况2：重启某个副本域的所有metaserver
Ditto

2023-11-14 09:39 UTC, SeanHai commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/10-curvefs-datapanel-config-metaserver.md
> +* 情况1：修改部分metaserver服务
Ditto

2023-11-14 09:39 UTC, SeanHai commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/10-curvefs-datapanel-config-metaserver.md
> +* 情况1：修改部分metaserver服务配置
Ditto （同时）

2023-11-14 09:39 UTC, SeanHai commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/11-curvefs-datapanel-upgrade-metaserver.md
> +* 情况2：升级某个副本域的所有metaserver
Ditto

2023-11-14 09:39 UTC, SeanHai commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/11-curvefs-datapanel-upgrade-metaserver.md
> +* 情况2：升级某个副本域的所有metaserver
Ditto

2023-11-14 09:39 UTC, SeanHai commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/15-curvefs-datapanel-change-disk.md
> +2. 拉起当前服务：
类似bs也需要检查盘的状态和缓存配置，并且需要将原来的data_dir重新挂载到新盘上

2023-11-14 09:41 UTC, SeanHai commented
Maybe some content about CSI and iscsi target

2023-11-15 10:49 UTC, aspirer commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/10-curvebs-datapanel-config-chunkserver.md
> +
那这个操作就是不建议按role指定重启了，否则会导致io hang，要写清楚

2023-11-15 10:49 UTC, aspirer commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/10-curvebs-datapanel-config-chunkserver.md
> +
这里也是io hang吧

2023-11-15 10:49 UTC, aspirer commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/11-curvebs-datapanel-upgrade-chunkserver.md
> +   --host: 升级指定主机的所有服务
这里缩进有问题

2023-11-15 11:16 UTC, caoxianfei1 commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/01-curvebs-controlpanel-start-mds.md
> +1. 查看集群状态和指定节点的mds状态：
fixed.

2023-11-15 11:16 UTC, caoxianfei1 commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/01-curvebs-controlpanel-start-mds.md
> +3. 再次查看集群状态，查看指定mds服务是否启动成功（Status为Up状态）：
fixed.

2023-11-15 11:21 UTC, caoxianfei1 commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/04-curvebs-controlpanel-config-mds.md
> +    提醒：该操作会重启机器中的所有mds服务，所以在执行下列操作时，可能会导致IO短暂时间的抖动。
这里只是想提示输入yes进行确认，已修改。
reload是全部实例一起重启。

2023-11-15 11:22 UTC, caoxianfei1 commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/05-curvebs-controlpanel-upgrade-mds.md
> +   $ cp topology.yaml topology.yaml.bak
fixed.

2023-11-15 12:29 UTC, caoxianfei1 commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/09-curvebs-datapanel-restart-chunkserver.md
> +* 情况2：重启某个副本域的所有chunkserver
fixed.

2023-11-15 12:29 UTC, caoxianfei1 commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/09-curvebs-datapanel-restart-chunkserver.md
> +* 情况2：重启某个副本域的所有chunkserver
fixed.

2023-11-15 12:29 UTC, caoxianfei1 commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/12-curvebs-datapanel-downgrade-chunkserver.md
> +* 情况2：回退某个副本域的所有chunkserver
fixed.

2023-11-15 12:29 UTC, caoxianfei1 commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/12-curvebs-datapanel-downgrade-chunkserver.md
> +* 情况2：回退某个副本域的所有chunkserver
fixed.

2023-11-15 12:31 UTC, caoxianfei1 commented
> miss the file 13-*** under BS and FS

fixed.

2023-11-16 01:53 UTC, caoxianfei1 commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/08-curvefs-datapanel-stop-metaserver.md
> +* 情况1：停止部分metaserver服务
fixed.

2023-11-16 08:16 UTC, xu-chaojie commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/23-curvebs-controlpanel-upgrade-snapshot.md
> +	--id: 升级指定 id 的服务
这个缩进看着不对，其他相似的文档也检查下有没有类似的问题

2023-11-16 08:21 UTC, xu-chaojie commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/24-curvebs-controlpanel-downgrade-snapshot.md
> +   注：如果集群不健康（error/warn状态），请不要回退。
这个句话感觉不太合适，集群不健康了，可能才需要回退，改一下表述，例如： 如果集群不健康，确认下是什么引起之后，如果是snapshotclone server引起，尝试回退。

2023-11-16 08:24 UTC, xu-chaojie commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/05-curvebs-controlpanel-upgrade-mds.md
> +       Do you want to continue? [yes/no]: (default=no)
建议把这个yes的说明放到curveadm upgrade --role mds上面的这里去，这条命令才是常规的升级步骤，后面两种只是可选步骤，区分下

2023-11-16 08:25 UTC, xu-chaojie commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/05-curvebs-controlpanel-upgrade-mds.md
> +	--id: 升级指定 id 的服务
缩进有问题，其他地方也看下

2023-11-20 09:01 UTC, caoxianfei1 commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/05-curvebs-controlpanel-upgrade-mds.md
> +	--id: 升级指定 id 的服务
fixed.

2023-11-20 09:01 UTC, caoxianfei1 commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/05-curvebs-controlpanel-upgrade-mds.md
> +       Do you want to continue? [yes/no]: (default=no)
fixed.

2023-11-20 09:01 UTC, caoxianfei1 commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/23-curvebs-controlpanel-upgrade-snapshot.md
> +	--id: 升级指定 id 的服务
fixed.

2023-11-20 09:06 UTC, caoxianfei1 commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/24-curvebs-controlpanel-downgrade-snapshot.md
> +   注：如果集群不健康（error/warn状态），请不要回退。
fixed.

2023-11-20 09:06 UTC, caoxianfei1 commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/11-curvebs-datapanel-upgrade-chunkserver.md
> +   --host: 升级指定主机的所有服务
fixed.

2023-11-20 09:06 UTC, caoxianfei1 commented on docs/02-CurveBS/07-maintenance/02-administrator-guide/10-curvebs-datapanel-config-chunkserver.md
> +
fixed.

2023-11-20 09:07 UTC, caoxianfei1 commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/15-curvefs-datapanel-change-disk.md
> +2. 拉起当前服务：
fixed.

2023-11-20 09:07 UTC, caoxianfei1 commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/11-curvefs-datapanel-upgrade-metaserver.md
> +* 情况2：升级某个副本域的所有metaserver
fixed.

2023-11-20 09:08 UTC, caoxianfei1 commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/11-curvefs-datapanel-upgrade-metaserver.md
> +* 情况2：升级某个副本域的所有metaserver
fixed.
upgrade 升级是滚动升级，所以使用curveadm命令不会出现升级涉及多个副本域的情况。

2023-11-20 09:08 UTC, caoxianfei1 commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/08-curvefs-datapanel-stop-metaserver.md
> +* 情况1：停止部分metaserver服务
fixed.

2023-11-20 09:08 UTC, caoxianfei1 commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/09-curvefs-datapanel-restart-metaserver.md
> +* 情况2：重启某个副本域的所有metaserver
fixed.

2023-11-20 09:08 UTC, caoxianfei1 commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/09-curvefs-datapanel-restart-metaserver.md
> +* 情况2：重启某个副本域的所有metaserver
fixed.

2023-11-20 09:08 UTC, caoxianfei1 commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/10-curvefs-datapanel-config-metaserver.md
> +* 情况1：修改部分metaserver服务
fixed.

2023-11-20 09:09 UTC, caoxianfei1 commented on docs/03-CurveFS/07-maintenance/02-administrator-guide/10-curvefs-datapanel-config-metaserver.md
> +* 情况1：修改部分metaserver服务配置
fixed.

2023-11-22 05:53 UTC, aspirer approved these changes

2023-11-22 05:58 UTC, merged