[doc]add asr usercase
opencurve/curve-book pull request #42
Opened 2023-11-21 07:25 UTC by Cyber-SiKu

2023-11-21 07:47 UTC, aspirer requested changes

2023-11-21 07:47 UTC, aspirer commented on docs/03-CurveFS/01-usecase/08-asr-storage.md
> +### CurveFS 优势
优势改成应用价值

2023-11-21 07:47 UTC, aspirer commented on docs/03-CurveFS/01-usecase/08-asr-storage.md
> +相较于本地存储而言，CurveFS 具有以下优势:
这里是本地存储，下面是对比3副本存储，需要统一。

2023-11-21 07:47 UTC, aspirer commented on docs/03-CurveFS/01-usecase/08-asr-storage.md
> +* 后端接入 NOS低频存储，相比3副本存储每年每 PB 数据存储可节约40%成本，大幅降低 ASR 训练存储成本
这里是3副本。上面是本地。我看他们原来是打算每个节点都放一份训练数据？

2023-11-21 07:47 UTC, aspirer commented on docs/03-CurveFS/01-usecase/08-asr-storage.md
> +* 支持数据多级缓存，提升训练并发效率
具体提升效果补充下

2023-11-21 07:47 UTC, aspirer commented on docs/03-CurveFS/01-usecase/08-asr-storage.md
> +与各类AI框架深度集成，提供自动化的数据预热、训练优化等功能,提升AI训练的易用性和效率。
格式需要改善，预览下看看。

2023-11-21 08:00 UTC, wuhongsong commented on docs/03-CurveFS/01-usecase/08-asr-storage.md
> +# CurveFS 助力网易云商，解决 ASR 训练数据增长需求
题目建议不要使用ASR缩写 -- 直接用人工智能 语音识别之类的  这样更吸引人？

2023-11-21 08:00 UTC, wuhongsong commented on docs/03-CurveFS/01-usecase/08-asr-storage.md
> +网易云商在发展 ASR 业务过程中，存储面临了巨大挑战。
遇到的这几个困难可以按照 "无序列表 "模式展示

2023-11-21 08:00 UTC, wuhongsong commented on docs/03-CurveFS/01-usecase/08-asr-storage.md
> +### CurveFS 优势
这里可以参考下https://kms.netease.com/article/88340  ， 内容更丰富一些

2023-11-21 11:18 UTC, Cyber-SiKu commented on docs/03-CurveFS/01-usecase/08-asr-storage.md
> +* 后端接入 NOS低频存储，相比3副本存储每年每 PB 数据存储可节约40%成本，大幅降低 ASR 训练存储成本
> 这里是3副本。上面是本地。我看他们原来是打算每个节点都放一份训练数据？

是的

2023-11-21 11:18 UTC, Cyber-SiKu commented on docs/03-CurveFS/01-usecase/08-asr-storage.md
> +### CurveFS 优势
> 优势改成应用价值

fix

2023-11-21 11:21 UTC, Cyber-SiKu commented on docs/03-CurveFS/01-usecase/08-asr-storage.md
> +* 支持数据多级缓存，提升训练并发效率
> 具体提升效果补充下

fix

2023-11-21 11:21 UTC, Cyber-SiKu commented on docs/03-CurveFS/01-usecase/08-asr-storage.md
> +与各类AI框架深度集成，提供自动化的数据预热、训练优化等功能,提升AI训练的易用性和效率。
> 格式需要改善，预览下看看。

fix

2023-11-21 11:22 UTC, Cyber-SiKu commented on docs/03-CurveFS/01-usecase/08-asr-storage.md
> +# CurveFS 助力网易云商，解决 ASR 训练数据增长需求
> 语音识别

fix

2023-11-21 11:22 UTC, Cyber-SiKu commented on docs/03-CurveFS/01-usecase/08-asr-storage.md
> +网易云商在发展 ASR 业务过程中，存储面临了巨大挑战。
> 遇到的这几个困难可以按照 "无序列表 "模式展示

fix

2023-11-21 11:25 UTC, Cyber-SiKu commented on docs/03-CurveFS/01-usecase/08-asr-storage.md
> +### CurveFS 优势
> 这里可以参考下https://kms.netease.com/article/88340 ， 内容更丰富一些

https://github.com/opencurve/curve-book/pull/43
已经使用了？

2023-11-22 02:33 UTC, wuhongsong approved these changes

2023-11-22 02:37 UTC, aspirer approved these changes

2023-11-22 02:37 UTC, merged