init docs dirs
opencurve/curve-book pull request #8
Opened 2023-08-02 03:39 UTC by aspirer

2023-08-02 12:53 UTC, h0hmj requested changes

2023-08-02 12:53 UTC, h0hmj commented on docs/01-intro.md
> +#  反馈及交流
这个是二级header吧 ##

2023-08-02 12:53 UTC, h0hmj commented on docs/01-intro.md
> +- [FAQ](https://docs.opencurve.io/category/FAQ)：主要根据User group中常见问题整理，还在逐步完善中。
faq页面看上去没有必要加一个category？一个md然后slug写/faq就行了，可以参考01-intro.md最开头的部分

2023-08-02 12:53 UTC, h0hmj commented on docs/02-CurveBS/01-scenario/_category_.json
> +  "label": "应用场景",
类似faq？可能不需要category，一个比较general的场景描述？细分的case好像已经有usercase了，或者这两个合并一下？

2023-08-02 12:53 UTC, h0hmj commented on docs/02-CurveBS/01-scenario/01-应用场景介绍.md
> +
文件名尽量英文吧

2023-08-02 12:53 UTC, h0hmj commented on docs/02-CurveBS/02-usecase/01-用户案例1.md
> +# 用户案例1
文件名: 用户案例 -> usecase

2023-08-02 12:53 UTC, h0hmj commented on docs/02-CurveBS/03-deploy/01-快速体验.md
> +#  CurveBS 快速体验
文件名：快速体验 -> quickstart

2023-08-02 12:53 UTC, h0hmj commented on docs/02-CurveBS/04-test/01-测试环境配置.md
> +# 测试环境配置
文件名：测试环境配置 -> test-setup

2023-08-02 12:53 UTC, h0hmj commented on docs/02-CurveBS/05-compare/01-CurveBS vs Ceph-rbd.md
> +**高性能 | 更稳定 | 易运维 | 云原生**
文件名：不要带空格
curvebs-vs-ceph-rbd

2023-08-02 12:53 UTC, h0hmj commented on docs/02-CurveBS/05-compare/_category_.json
> +  "label": "对比",
对比 -> 同类软件对比 ?

2023-08-02 12:53 UTC, h0hmj commented on docs/02-CurveBS/06-arch/01-架构介绍.md
> +# 架构介绍
文件名：架构介绍 -> arch-intro

2023-08-02 12:53 UTC, h0hmj commented on docs/02-CurveBS/07-perf/01-性能测试介绍.md
> +
文件名：性能测试介绍 -> perf-benchmark-intro

介绍怎么做benchmark的？

2023-08-02 12:53 UTC, h0hmj commented on docs/02-CurveBS/08-operation/01-运维工具介绍.md
> +
文件名：运维工具 -> maintenance-tools

2023-08-02 12:53 UTC, h0hmj commented on docs/03-CurveFS/01-scenario/01-应用场景介绍.md
> +
同curvebs的相同部分，还有下面的usecase
以及后续的文件名

2023-08-02 12:53 UTC, h0hmj commented on docs/02-CurveBS/07-perf/_category_.json
> +  "label": "性能",
性能是不是丢到测试下面的子类里去，不是很确定

2023-08-02 12:53 UTC, h0hmj commented on docs/03-CurveFS/05-compare/01-CurveFS vs CephFS.md
> +
curvefs-vs-cephfs

2023-08-02 12:53 UTC, h0hmj commented on docs/04-rdma+spdk/_category_.json
> +  "label": "RDMA高性能块存储",
rdma要一级目录单列吗

2023-08-02 12:53 UTC, h0hmj commented on docs/07-release/02-releasenotes-v2.6.md
> +> TBD
releasenotes -> release-notes

2023-08-02 12:53 UTC, h0hmj commented on docs/08-FAQ/01-FAQ.md
> +
faq参考intro里的意见

2023-08-03 01:18 UTC, aspirer commented on docs/01-intro.md
> +#  反馈及交流
一二级都行吧，本来我是想放在一级的

2023-08-03 01:18 UTC, aspirer commented on docs/01-intro.md
> +- [FAQ](https://docs.opencurve.io/category/FAQ)：主要根据User group中常见问题整理，还在逐步完善中。
OK

2023-08-03 01:18 UTC, aspirer commented on docs/02-CurveBS/01-scenario/_category_.json
> +  "label": "应用场景",
合并掉吧，改成：应用场景及案例

2023-08-03 01:18 UTC, aspirer commented on docs/02-CurveBS/01-scenario/01-应用场景介绍.md
> +
ok

2023-08-03 01:19 UTC, aspirer commented on docs/02-CurveBS/07-perf/_category_.json
> +  "label": "性能",
可能还有些怎么分析metric指标、调优性能之类的指导文档，单列吧

2023-08-03 01:19 UTC, aspirer commented on docs/03-CurveFS/05-compare/01-CurveFS vs CephFS.md
> +
ok

2023-08-03 01:20 UTC, aspirer commented on docs/04-rdma+spdk/_category_.json
> +  "label": "RDMA高性能块存储",
最好单列吧，目前还没开源

2023-08-03 01:20 UTC, aspirer commented on docs/07-release/02-releasenotes-v2.6.md
> +> TBD
ok

2023-08-03 01:48 UTC, h0hmj commented on docs/01-intro.md
> +#  反馈及交流
一级 = 文章标题

2023-08-03 02:05 UTC, aspirer commented on docs/01-intro.md
> +#  反馈及交流
那就尴尬了，我以为是右侧边栏的目录里面的一二级。我还专门改了几个地方，还有别的示例文档也有类似问题的。

2023-08-03 04:45 UTC, h0hmj approved these changes

2023-08-03 04:46 UTC, merged